# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import calculator_pb2 as calculator__pb2


class CalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SolveStream = channel.stream_stream(
            "/Calculator/SolveStream",
            request_serializer=calculator__pb2.Calculation.SerializeToString,
            response_deserializer=calculator__pb2.Solution.FromString,
        )


class CalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SolveStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SolveStream": grpc.stream_stream_rpc_method_handler(
            servicer.SolveStream,
            request_deserializer=calculator__pb2.Calculation.FromString,
            response_serializer=calculator__pb2.Solution.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Calculator", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SolveStream(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/Calculator/SolveStream",
            calculator__pb2.Calculation.SerializeToString,
            calculator__pb2.Solution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
