# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"\"\n\x0b\x43\x61lculation\x12\x13\n\x0b\x63\x61lculation\x18\x01 \x01(\t\".\n\x08Solution\x12\x10\n\x08solvable\x18\x01 \x01(\x08\x12\x10\n\x08solution\x18\x02 \x01(\x02\x32:\n\nCalculator\x12,\n\x0bSolveStream\x12\x0c.Calculation\x1a\t.Solution\"\x00(\x01\x30\x01\x62\x06proto3')



_CALCULATION = DESCRIPTOR.message_types_by_name['Calculation']
_SOLUTION = DESCRIPTOR.message_types_by_name['Solution']
Calculation = _reflection.GeneratedProtocolMessageType('Calculation', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATION,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Calculation)
  })
_sym_db.RegisterMessage(Calculation)

Solution = _reflection.GeneratedProtocolMessageType('Solution', (_message.Message,), {
  'DESCRIPTOR' : _SOLUTION,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Solution)
  })
_sym_db.RegisterMessage(Solution)

_CALCULATOR = DESCRIPTOR.services_by_name['Calculator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALCULATION._serialized_start=20
  _CALCULATION._serialized_end=54
  _SOLUTION._serialized_start=56
  _SOLUTION._serialized_end=102
  _CALCULATOR._serialized_start=104
  _CALCULATOR._serialized_end=162
# @@protoc_insertion_point(module_scope)
